#!/usr/bin/env python3

import subprocess

def get_command_result(command)-> str:
    return subprocess.run(command, shell=True, capture_output=True, text=True).stdout.strip()

players = subprocess.run("playerctl --list-all", shell=True, capture_output=True, text=True).stdout.split("\n")

for player in players:
    status = get_command_result(f"playerctl status -p {player}")

    if status != "Stopped" and status != "":
        print(" 󰒮 ", flush=True)
        exit(0)

print("", flush=True)
exit(0)   
